module ChatNames::Wow
  def self.key
    'wow'
  end

  def self.included(base)
    base.names[self.key] = 
      [
        "阿达尔（A'dal）",
        "艾萨斯·夺日者（Aethas Sunreaver）",
        "阿格娜",
        "风领主奥拉基尔",
        "观察者奥尔加隆（Algalon the Observer）",
        "奥蕾莉亚·风行者（Alleria Windrunner）",
        "亚历山德罗斯·莫格莱尼（Alexandros Mograine）",
        "阿莱克斯塔萨（Alexstrasza）",
        "阿隆索斯·法奥（Alonsus Fao）",
        "阿卡玛（Akama）",
        "阿纳克洛斯（Anachronos）",
        "安纳斯特里亚·逐日者（Anasterian Sunstrider）",
        "安度因·洛萨（Anduin Lothar）",
        "安度因·乌瑞恩（Anduin Wrynn）",
        "安东尼达斯（Antonidas）",
        "阿努巴拉克（Anub'arak）",
        "安薇娜（Anveena Teague）",
        "阿克蒙德（Archimonde）",
        "阿尔萨斯·米奈希尔",
        "阿鲁高（Arugal）",
        "亚雷苟斯（Arygos）",
        "艾萨拉（Azshara）",
        "贝恩·血蹄（Baine Bloodhoof）",
        "巴纳扎尔（Balnazzar）",
        "伯瓦尔·弗塔根（Bolvar Fordragon）",
        "布莱恩·铜须（Brann Bronzebeard）",
        "布罗尔·熊皮（Broll Bearmantle）",
        "布洛克斯希加·萨鲁法尔",
        "巴德（Budd）",
        "凯雷斯特拉兹（Caelestrasz）",
        "塞纳留斯（Cenarius）",
        "古加尔（Cho'gall）",
        "克苏恩（C'Thun）",
        "陈·风暴烈酒（Chen Stormstout）",
        "戴林·普罗德摩尔（Daelin Proudmoore）",
        "达纳斯·托尔贝恩（Danath Trollbane）",
        "达尔坎·德拉希尔（Dar'Khan Drathir）",
        "达斯雷玛·逐日者（Dath'Remar Sunstrider）",
        "德赛洛克（Detheroc）",
        "德拉诺斯·萨鲁法尔（Dranosh Saurfang）",
        "德雷克塔尔（Drek'thar",
        "杜隆坦（Durotan）",
        "伊崔格（Eitrigg）",
        "艾露恩（Elune）",
        "伊兰尼库斯（Eranikus）",
        "弗斯塔德·蛮锤（Falstad Wildhammer）",
        "范达尔·鹿盔（Fandral Staghelm）",
        "迦拉克隆（Galakrond）",
        "加里维克斯（Gallywix）",
        "加兹鲁维（Gazlowe）",
        "加里索斯（Garithos）",
        "迦罗娜·半血（Garona Halforcen）",
        "加尔鲁什·地狱咆哮（Garrosh Hellscream）",
        "格尔宾·梅卡托克（Gelbin Mekkatorque）",
        "吉恩·格雷迈恩（Genn Greymane）",
        "格罗玛什·地狱咆哮（Grommash Hellscream ）",
        "格鲁尔（Gruul）",
        "古尔丹（Gul'dan）",
        "哈杜伦·明翼（Halduron Brightwing）",
        "哈缪尔·符文图腾（Hamuul Runetotem）",
        "伊利丹·怒风(Illidan Stormrage)",
        "吉安娜·普罗德摩尔(Jaina Proudmoore)",
        "凯尔萨斯·逐日者(Kael'thas Sunstrider)",
        "科尔苏加德(Kel'thuzad)",
        "库德兰·蛮锤(Kurdran Wildhammer)",
        "基尔罗格·死眼(Kilrogg Deadeye)",
        "克莱奥斯特拉兹(Korialstrasz)",
        "基尔加丹(Kil'jaeden)",
        "卡德加(Khadgar)",
        "莉雅德伦(Lady Liadrin)",
        "洛瑟玛·塞隆(Lor'themar Theron)",
        "露娜拉(Lunara)",
        "莉莉•风暴烈酒(Lili Stormstout)",
        "玛维·影歌(Maiev Shadowsong)",
        "玛法里奥·怒风(Malfurion Stormrage)",
        "玛尔加尼斯(Mal'Ganis)",
        "麦格尼·铜须(Magni Bronzebeard)",
        "玛诺洛斯（Mannoroth)",
        "麦德安（Med'an）",
        "麦迪文（Medivh）",
        "穆拉丁·铜须（Muradin Bronzebeard）",
        "美猴王（Monkey King）",
        "纳兹格雷尔（Nazgrel）",
        "诺兹多姆（Nozdormu）",
        "努波顿（Nobundo）",
        "奈法利安（Nefarian）",
        "奈萨里奥（Neltharion）",
        "耐奥祖（Ner'zhul）",
        "奥格瑞姆·毁灭之锤（Orgrim Doomhammer）",
        "普特雷斯（Putress）",
        "拉格纳罗斯（Ragnaros）",
        "雷克萨（Rexxar）",
        "罗甯（Rhonin）",
        "洛摩斯（Rommath）",
        "莎莉·怀特迈恩（Sally Whitemane）",
        "萨格拉斯（Sargeras）",
        "希尔瓦娜斯·风行者（Sylvanas Windrunner）",
        "辛萨莉雅(Sintharia)",
        "缝合怪",
        "泰兰德·语风(Tyrande Whisperwind)",
        "提克迪奥斯(Tichondrius)",
        "提里奥·弗丁（Tirion Fordring）",
        "图拉扬（Turalyon）",
        "萨尔（Thrall/Go'el）",
        "塔兰•祝（Taran Zhu）",
        "乌瑟尔（Uther）",
        "瓦莉拉·桑古纳尔",
        "瓦里安·乌瑞恩（Varian Wrynn）",
        "瓦里玛萨斯（Varimathras）",
        "瓦许女士（Lady Vashj）",
        "温蕾萨·风行者（Vereesa Windrunner）",
        "瓦洛克·萨鲁法尔（Varok Saurfang）",
        "守备官玛尔拉德（Vindicator Maraad）",
        "沃金（Vol'jin）",
        "哈维斯（Xavius）",
        "伊瑟拉（Ysera）",
        "祖尔金（Zul'jin）",
        "祖鲁希德（Zuluhed）"
      ]
    end
end

