version: '2'
services:
  db:
    image: mysql
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
  web:
    build: ./poker
    command: bundle exec rails s -p 3000 -b 0.0.0.0
    volumes:
      - .:/poker
    ports:
      - "3334:3000"
    links:
      - db
