version: '2'
services:
  db:
    container_name: poker_db_production
    image: mysql
    ports:
      - "3306"
    volumes:
      - ./my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
  app:
    container_name: poker_app_production
    build: ./
    command: bundle exec rails s -p 3000 -b 0.0.0.0 -e production
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    links:
      - db
  nginx:
    container_name: poker_nginx_production
    image: nginx
    volumes_from:
      - app
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80