version: '2'
services:
  db:
    image: mysql
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
  app:
    build: ./poker
    command: bundle exec rails s -p 3000 -b 0.0.0.0
    volumes:
      - ./poker:/usr/src/app
    ports:
      - "3000:3000"
    links:
      - db
  nginx:
    image: nginx
    volumes_from:
      - app
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80